apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: privileged
  name: perf
  labels:
    app: perf
  namespace: my-perf-project
spec:
  securityContext: 
    privileged: true
  hostNetwork: true
  hostPID: true
  containers:
    - name: perf
      imagePullPolicy: Always
      image: quay.io/bpradipt/perf:latest
      securityContext: 
        capabilities:
          add: ["CAP_SYS_ADMIN"]
      ports:
        - containerPort: 8080
